create table if not exists public.pinecone_records (
    id bigint generated by default as identity primary key,
    document_id text not null,
    document_name text not null,
    document_type text,
    collection text not null,
    hash bpchar,
    uploaded_by text,
    uploaded_at timestamptz
);

create table if not exists public.retrieval_result_logs (
    id bigint generated by default as identity primary key,
    request_id text not null,
    workflow_type text not null,
    query_text text not null,
    provider text,
    model text,
    collection text,
    result_index integer not null,
    document_id text,
    doc_name text,
    page_number integer,
    score double precision,
    created_at timestamptz not null default now()
);

create index if not exists idx_pinecone_records_document_id
    on public.pinecone_records (document_id);

create index if not exists idx_pinecone_records_collection
    on public.pinecone_records (collection);

create index if not exists idx_retrieval_result_logs_request_id
    on public.retrieval_result_logs (request_id);

create index if not exists idx_retrieval_result_logs_document_id
    on public.retrieval_result_logs (document_id);

alter table public.pinecone_records enable row level security;
alter table public.retrieval_result_logs enable row level security;

comment on table public.pinecone_records is
    'Internal record of documents indexed into Pinecone. Intended for backend or service-role access only by default.';

comment on table public.retrieval_result_logs is
    'Internal retrieval trace log. Intended for backend or service-role access only by default.';
